"""
Mathematical archetypes and quantitative hypotheses for Options Alpha generation.
Each archetype represents a structural derivatives-pricing edge with proven institutional
and academic pedigree, incorporating principles from Options Master Knowledge Base (Books 1-4).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class OptionArchetype:
    name: str
    category: str
    description: str
    economic_rationale: str
    formula_template: str
    typical_horizons: list[int]
    neutralization_groups: list[str]
    is_high_confidence: bool = False


ARCHETYPES: list[OptionArchetype] = [
    OptionArchetype(
        name="Synthetic Forward Basis Spread",
        category="forward_basis",
        description="Spread between synthetic forward price from put-call parity and spot price.",
        economic_rationale="Options market synthetic forwards reflect institutional consensus drift expectations.",
        formula_template="group_neutralize(rank((forward_price_{tenor} - close) / close), {group})",
        typical_horizons=[10, 20, 30, 60, 90],
        neutralization_groups=["sector", "industry", "subindustry"],
    ),
    OptionArchetype(
        name="Forward Basis Velocity",
        category="forward_basis",
        description="Rate of change in synthetic forward basis over trailing window.",
        economic_rationale="Accelerating forward basis reveals institutional accumulation before spot breakout.",
        formula_template="group_neutralize(rank(ts_delta((forward_price_{tenor} - close) / close, {window})), {group})",
        typical_horizons=[10, 20, 30],
        neutralization_groups=["sector", "subindustry"],
    ),
    OptionArchetype(
        name="Put-Call Ratio Contrarian Reversal",
        category="pcr_flow",
        description="Normalized z-score of put-to-call volume ratio.",
        economic_rationale="Extreme spikes in put volume signal capitulation and provide high-conviction squeeze setups.",
        formula_template="group_neutralize(rank(-ts_zscore(pcr_vol_{tenor}, {window})), {group})",
        typical_horizons=[10, 20, 30],
        neutralization_groups=["sector", "industry", "subindustry"],
    ),
    OptionArchetype(
        name="PCR Volume-to-OI Flow Surge",
        category="pcr_flow",
        description="Ratio of daily put-call volume to open interest stock.",
        economic_rationale="Unusual trading velocity in puts relative to existing open interest reveals aggressive smart-money flow.",
        formula_template="group_neutralize(rank(-ts_rank(pcr_vol_{tenor} / (pcr_oi_{tenor} + 0.001), {window})), {group})",
        typical_horizons=[10, 20, 30],
        neutralization_groups=["sector", "subindustry"],
    ),
    OptionArchetype(
        name="Volatility Skew Steepness Shock",
        category="skew",
        description="Change in downside OTM put skew steepness.",
        economic_rationale="Sudden steepening of the skew indicates institutional demand for downside crash protection.",
        formula_template="group_neutralize(rank(-ts_delta(implied_volatility_mean_skew_{tenor}, {window})), {group})",
        typical_horizons=[10, 20, 30, 60],
        neutralization_groups=["sector", "subindustry"],
    ),
    OptionArchetype(
        name="Sqrt-T Normalized Skew Acceleration",
        category="skew",
        description="Downside skew steepness normalized by the square root of expiration time.",
        economic_rationale="Cross-book high confidence principle: skew mathematically decays with sqrt(T). Normalizing isolates true tail risk without double-counting volatility.",
        formula_template="group_neutralize(rank(-ts_delta(implied_volatility_mean_skew_{tenor} * sqrt({tenor} / 252.0), {window})), {group})",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Call Breakeven Hurdle Spread",
        category="breakeven",
        description="Percentage distance from forward to open-interest weighted call breakeven price.",
        economic_rationale="Demeaned distance to call breakeven reflects expected upside target priced by option writers.",
        formula_template="group_neutralize(rank((call_breakeven_{tenor} - forward_price_{tenor}) / forward_price_{tenor}), {group})",
        typical_horizons=[10, 20, 30, 60, 90],
        neutralization_groups=["sector", "subindustry"],
    ),
    OptionArchetype(
        name="Call Breakeven Hurdle Acceleration",
        category="breakeven",
        description="Rate of change in open-interest weighted call breakeven hurdle.",
        economic_rationale="Rapidly shifting call breakeven targets signal market makers adjusting upper strike barriers ahead of moves.",
        formula_template="group_neutralize(rank(ts_delta((call_breakeven_{tenor} - forward_price_{tenor}) / forward_price_{tenor}, {window})), {group})",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Liquidity-Gated Breakeven Surge",
        category="breakeven",
        description="Call breakeven hurdle filtered by volume surge condition.",
        economic_rationale="Options breakeven upside signals are most actionable when trading volume confirms active participation.",
        formula_template="trade_when(volume > adv20, group_neutralize(rank((call_breakeven_{tenor} - forward_price_{tenor}) / forward_price_{tenor}), {group}), -1)",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["sector", "subindustry"],
    ),
    OptionArchetype(
        name="Volatility Term Structure Slope",
        category="term_structure",
        description="Ratio of front-month implied volatility to 3-month implied volatility.",
        economic_rationale="Inversion of IV term structure (front-month > 3-month) indicates temporary panic pricing that mean-reverts.",
        formula_template="group_neutralize(rank(-(implied_volatility_mean_30 / (implied_volatility_mean_90 + 0.001) - 1.0)), {group})",
        typical_horizons=[30],
        neutralization_groups=["sector", "subindustry"],
    ),
    OptionArchetype(
        name="Pairwise Forward Volatility Term Notch",
        category="term_structure",
        description="Notch between front-month and intermediate forward volatility derived from term structure variance.",
        economic_rationale="Forward volatility extracted across tenors isolates scheduled catalyst risk and event mispricing.",
        formula_template="group_neutralize(rank(-(sqrt(max(0.0001, (signed_power(implied_volatility_mean_90, 2) * 90 - signed_power(implied_volatility_mean_30, 2) * 30) / 60)) - implied_volatility_mean_30)), {group})",
        typical_horizons=[30],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Variance Risk Premium (IV vs RV)",
        category="term_structure",
        description="Difference between implied volatility and rolling realized volatility.",
        economic_rationale="Stocks with excessively high IV over realized volatility suffer from option overpricing, predicting subdued return drag.",
        formula_template="group_neutralize(rank(-(implied_volatility_mean_{tenor} - ts_std_dev(returns, {window}) * 15.87)), {group})",
        typical_horizons=[20, 30],
        neutralization_groups=["sector", "industry"],
    ),
    OptionArchetype(
        name="Jensen-Debiased Variance Risk Premium",
        category="term_structure",
        description="VRP adjusted for small-sample downward bias in realized volatility estimator.",
        economic_rationale="Jensen's inequality causes short-window realized volatility to systematically underestimate true volatility; debiasing eliminates false-positive VRP richness.",
        formula_template="group_neutralize(rank(-(implied_volatility_mean_{tenor} - ts_std_dev(returns, {window}) * 16.53)), {group})",
        typical_horizons=[20, 30],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Optimal Mean-Reversion Threshold Gated VRP",
        category="term_structure",
        description="Variance risk premium entry conditioned on crossing the ~0.75 SD optimal threshold.",
        economic_rationale="Institutional derivation from Sinclair (Book 1): for mean-reverting processes, entering at ~0.75 SD maximizes expected growth by balancing edge with trading opportunity count.",
        formula_template="trade_when(abs(ts_zscore(implied_volatility_mean_30 - ts_std_dev(returns, 30) * 15.87, 40)) > 0.75, group_neutralize(rank(-(implied_volatility_mean_30 - ts_std_dev(returns, 30) * 15.87)), {group}), -1)",
        typical_horizons=[30],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Parkinson Extreme-Value Volatility Premium",
        category="term_structure",
        description="Spread between implied volatility and Parkinson extreme-value intraday realized volatility.",
        economic_rationale="Parkinson volatility is 5x more efficient than close-to-close metrics; fading overpriced IV vs Parkinson RV isolates persistent risk premia.",
        formula_template="group_neutralize(rank(ts_decay_linear(-(implied_volatility_mean_{tenor} / (parkinson_volatility_{tenor} + 0.001) - 1.0), 5)), {group})",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Call-Put Implied Volatility Asymmetry",
        category="skew",
        description="Normalized divergence between OTM call implied volatility and put implied volatility.",
        economic_rationale="Shifts in call IV relative to put IV reflect directional options flow and speculative upside demand.",
        formula_template="group_neutralize(rank(ts_decay_linear((implied_volatility_call_{tenor} - implied_volatility_put_{tenor}) / (implied_volatility_mean_{tenor} + 0.001), 5)), {group})",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Liquidity-Gated Breakeven Acceleration",
        category="breakeven",
        description="OI-weighted call breakeven rate of change gated by liquidity and smoothed by linear decay.",
        economic_rationale="High-conviction breakeven repricing combined with trading volume confirmation yields maximum Sharpe and minimal turnover.",
        formula_template="trade_when(volume > adv20, group_neutralize(rank(ts_decay_linear(ts_delta((call_breakeven_{tenor} - forward_price_{tenor}) / forward_price_{tenor}, {window}), 5)), {group}), -1)",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["sector", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Pan-Poteshman Informed Option Flow",
        category="pcr_flow",
        description="Buyer-initiated put-call volume to open interest surge gated by underlying liquidity.",
        economic_rationale="Pan & Poteshman (2006, Journal of Finance): institutional option volume initiated to open new positions leads stock prices by up to 40 bps on the next day.",
        formula_template="trade_when(volume > adv20, group_neutralize(rank(-ts_decay_linear(pcr_vol_{tenor} / (pcr_oi_{tenor} + 0.001), 5)), {group}), -1)",
        typical_horizons=[10, 20, 30],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Xing-Zhang-Zhao Volatility Smirk Smear",
        category="skew",
        description="Square-root-time scaled implied volatility smirk steepness.",
        economic_rationale="Xing, Zhang, & Zhao (2010, JFQA): individual volatility smirk steepness directly predicts future downward jumps and negative earnings surprises.",
        formula_template="group_neutralize(rank(-ts_decay_linear(implied_volatility_mean_skew_{tenor} * sqrt({tenor} / 252.0), 5)), {group})",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["subindustry", "industry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Bali-Hovakimian Volatility Spread PC3",
        category="skew",
        description="Call implied volatility minus put implied volatility orthogonal directional spread.",
        economic_rationale="Bali & Hovakimian (2009, Management Science): the call-put volatility spread constitutes an independent principal component forecasting underlying equity returns.",
        formula_template="group_neutralize(rank(ts_decay_linear((implied_volatility_call_{tenor} - implied_volatility_put_{tenor}) / (implied_volatility_mean_{tenor} + 0.001), 5)), {group})",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Carr-Wu Quadratic Variance Risk Premium",
        category="term_structure",
        description="Synthetic variance swap rate (IV squared) minus rolling realized return variance.",
        economic_rationale="Carr & Wu (2009, Review of Financial Studies): synthetic variance swap replication shows that variance risk premium is quadratic in implied volatility.",
        formula_template="group_neutralize(rank(-(signed_power(implied_volatility_mean_{tenor}, 2) - signed_power(ts_std_dev(returns, {window}), 2) * 252)), {group})",
        typical_horizons=[20, 30],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Tulchinsky Winsorized Robust Breakeven",
        category="breakeven",
        description="Call breakeven distance smoothed with robust linear decay and volume gating.",
        economic_rationale="Igor Tulchinsky et al. (2019, Finding Alphas Ch. 12): robust estimators and decay operators suppress quote noise and prevent backtest overfitting in WebSim.",
        formula_template="trade_when(volume > adv20, group_neutralize(rank(ts_decay_linear((call_breakeven_{tenor} - forward_price_{tenor}) / forward_price_{tenor}, 5)), {group}), -1)",
        typical_horizons=[20, 30, 60],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Analyst Revision Momentum",
        category="analyst_revisions",
        description="Consensus earnings forecast revision drift over multi-week lookbacks.",
        economic_rationale="Givoly & Lakonishok (1979): Sell-side analysts revise forecasts in sluggish autocorrelation clusters; positive revision ratios predict multi-month abnormal drift.",
        formula_template="group_neutralize(rank(ts_decay_linear((est_eps - ts_delay(est_eps, {window})) / (abs(ts_delay(est_eps, {window})) + 0.01), {decay})), {group})",
        typical_horizons=[15, 30, 60],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Analyst Dispersion Fade",
        category="analyst_revisions",
        description="Standard deviation of consensus EPS forecasts normalized by mean expectation.",
        economic_rationale="Diether, Malloy, & Scherbina (2002): High analyst disagreement indicates price over-optimism under short-sale constraints; fading high-dispersion names delivers persistent alpha.",
        formula_template="group_neutralize(rank(-ts_decay_linear(std_dev_eps_est / (abs(est_eps) + 0.01), {decay})), {group})",
        typical_horizons=[30, 60, 90],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Price Target Implied Upside",
        category="analyst_revisions",
        description="Consensus price target upside conditioned on trailing price velocity.",
        economic_rationale="Fabozzi et al. (2010): Consensus price target upside reflects institutional target prices, and conditioning on non-negative momentum eliminates value traps.",
        formula_template="trade_when(ts_delta(close, {window}) > 0, group_neutralize(rank(ts_decay_linear((target_price - close) / close, {decay})), {group}), -1)",
        typical_horizons=[10, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Short Demand Borrow Surge",
        category="short_interest",
        description="Institutional borrow fee acceleration interacted with short interest scale.",
        economic_rationale="Cohen, Diether, & Malloy (2007): Inward shifts in short lending supply combined with outward shifts in borrowing demand isolate high-conviction institutional shorting.",
        formula_template="group_neutralize(rank(-ts_decay_linear(borrow_fee * (short_interest / (float_shares + 0.001)), {decay})), {group})",
        typical_horizons=[10, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="De-Trended Short Interest Z-Score",
        category="short_interest",
        description="Short interest ratio standardized against trailing historical distribution.",
        economic_rationale="Rapach, Ringgenberg, & Zhou (2016): De-trended 126d/252d short interest Z-score measures abnormal institutional positioning free of structural drift.",
        formula_template="group_neutralize(rank(-ts_decay_linear(ts_zscore(short_interest / (float_shares + 0.001), {window}), {decay})), {group})",
        typical_horizons=[126, 252],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Days-to-Cover Short Squeeze Breakout",
        category="short_interest",
        description="High days-to-cover short interest triggered on upward price breakouts.",
        economic_rationale="Asquith, Pathak, & Ritter (2005) & Kathryn Staley (1997): Trapped short sellers face forced margin buy-ins when positive price breakouts occur on heavy days-to-cover stocks.",
        formula_template="trade_when((close > ts_mean(close, {window})) & (days_to_cover > 5.0), group_neutralize(rank(ts_decay_linear(days_to_cover * ts_delta(close, 5), {decay})), {group}), -1)",
        typical_horizons=[10, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Volatility Smirk Borrow Fee Hybrid",
        category="hybrid_confluence",
        description="Cross-asset confluence of downside options skew and institutional equity borrow fees.",
        economic_rationale="Cross-market information transmission: Downside put skew and borrow fee spikes both reflect informed hedging; when they coincide, downside conviction reaches maximum power.",
        formula_template="group_neutralize(rank(-ts_decay_linear((implied_volatility_mean_skew_30 * sqrt(30 / 252.0)) * (borrow_fee + 1.0), {decay})), {group})",
        typical_horizons=[20, 30],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Revision vs Skew Divergence Hybrid",
        category="hybrid_confluence",
        description="Misalignment between sell-side price target upgrades and options market downside hedging.",
        economic_rationale="Derivatives market participants empirically lead cash analyst revisions by 10-20 trading days; fading analyst upgrades met with expanding downside put skew exploits structural lag.",
        formula_template="group_neutralize(rank(ts_decay_linear((est_eps - ts_delay(est_eps, {window})) / (abs(ts_delay(est_eps, {window})) + 0.01) - (implied_volatility_mean_skew_30 * sqrt(30 / 252.0)), {decay})), {group})",
        typical_horizons=[20, 30],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Institutional Ownership Breadth Delta",
        category="institutional_13f_breadth",
        description="Growth in the number of unique institutional holders from 13F filings.",
        economic_rationale="Chen, Hong, & Stein (2002): An increase in institutional breadth signals broad-based fund adoption, relieving short-sale constraints and forecasting multi-month drift.",
        formula_template="group_neutralize(rank(ts_decay_linear((inst_owners_count - ts_delay(inst_owners_count, {window})) / (ts_delay(inst_owners_count, {window}) + 1.0), {decay})), {group})",
        typical_horizons=[30, 60],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Opportunistic Insider Cluster Buying",
        category="insider_cluster_buying",
        description="Open-market purchases by multiple corporate executives simultaneously.",
        economic_rationale="Cohen, Malloy, & Pomorski (2012) & Lakonishok & Lee (2001): Opportunistic open-market cluster buying by C-suite officers contains strong asymmetric predictive power for forward returns.",
        formula_template="trade_when(insider_buy_count >= 2, group_neutralize(rank(ts_decay_linear(insider_buy_shares / (adv20 + 1.0), {decay})), {group}), -1)",
        typical_horizons=[20, 30],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Post-Earnings Announcement Volatility Drift",
        category="peavd_earnings_vol_drift",
        description="Earnings surprises scaled by front-to-back implied volatility term structure slope.",
        economic_rationale="Ball & Brown (1968) & Patel & Wolfson (1984): Markets under-react to earnings surprises; scaling by IV term slope confirms persistent institutional demand during post-earnings drift.",
        formula_template="group_neutralize(rank(ts_decay_linear(ts_zscore(eps_surprise, {window}) * (implied_volatility_mean_30 / (implied_volatility_mean_90 + 0.001)), {decay})), {group})",
        typical_horizons=[40, 60],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Model-Free Jump Variance Curvature",
        category="jump_variance_moments",
        description="Model-free jump variance curvature decomposed from option surface cross-sections.",
        economic_rationale="Carr & Madan (2001) & Bollerslev, Tauchen, & Zhou (2009): Cross-sectional differences in discontinuous jump variance capture tail-risk compensation unpriced by linear models.",
        formula_template="group_neutralize(rank(ts_decay_linear(implied_volatility_put_30 * implied_volatility_put_30 - 2.0 * implied_volatility_mean_30 * implied_volatility_mean_30 + implied_volatility_call_30 * implied_volatility_call_30, {decay})), {group})",
        typical_horizons=[15, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Innovative Efficiency Ratio",
        category="patent_innovation_efficiency",
        description="Patent grant and citation output scaled against cumulative R&D investment.",
        economic_rationale="Cohen, Diether, & Malloy (2013) & Hirshleifer, Hsu, & Li (2013): Markets misvalue intangible R&D capital; firms with high patent conversion efficiency deliver superior multi-quarter alpha.",
        formula_template="group_neutralize(rank(ts_decay_linear(patent_count / (ts_decay_linear(rd_expenditure, 252) + 1.0), {decay})), {group})",
        typical_horizons=[40, 60],
        neutralization_groups=["industry", "subindustry"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Dynamic Short Squeeze S-Curve",
        category="dynamic_short_squeeze",
        description="Nonlinear interaction of high borrow fees, elevated days-to-cover, and upside price breakouts.",
        economic_rationale="Engelberg, Reed, & Ringgenberg (2018): Short sellers face non-linear convexity of forced margin liquidation as borrow fees spike during upward momentum.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(borrow_fee * (short_interest / (float_shares + 0.001)) * ts_delta(close, {window}), {decay})), {group}), -1)",
        typical_horizons=[5, 10, 15],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="VPIN Informed Order Flow Toxicity",
        category="order_flow_vpin",
        description="Volume-synchronized probability of toxicity proxy derived from unsigned volume and directional variance.",
        economic_rationale="Easley, Lopez de Prado, & O'Hara (2012): Informed traders cluster trades, generating high VPIN and pre-empting adverse price dislocations.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(abs(ts_delta(close, 1)) / (high - low + 0.001) * (volume / (adv20 + 0.001)) * sign(returns), {decay})), {group}), -1)",
        typical_horizons=[5, 10, 15],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Gamma Pinning Strike Magnetism",
        category="gamma_pinning_clustering",
        description="Market maker gamma imbalance clustering around major open interest strikes at expiration.",
        economic_rationale="Ni, Pearson, & Poteshman (2005): Option market makers delta-hedging large gamma inventories systematically pin stock prices near max-OI strikes at expiry.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(-abs((close - (call_breakeven_30 + put_breakeven_30) / 2.0) / close), {decay})), {group}), -1)",
        typical_horizons=[5, 10, 15],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Customer-Supplier Information Cascades",
        category="customer_supplier_cascades",
        description="Supply chain momentum diffusion from lead customers into downstream suppliers.",
        economic_rationale="Fee & Thomas (2004) & Menzly & Ozbas (2010): Economic linkages across customer-supplier networks cause shocks to propagate with a 5-20 day information lag.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(ts_delay(group_mean(returns, 20, {group}), 5) - returns, {decay})), {group}), -1)",
        typical_horizons=[10, 15, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="R&D Capitalization Intensity",
        category="rd_capitalization_spillovers",
        description="Intangible knowledge capital accumulation and technology spillovers.",
        economic_rationale="Lev & Sougiannis (1996) & Bloom et al. (2013): Markets under-react to the multi-year value creation of cumulative R&D investments.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(ts_mean(rd_expense / (total_assets + 1.0), 60), {decay})), {group}), -1)",
        typical_horizons=[15, 20, 25],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Total Asset Growth Drag Anomaly",
        category="capex_asset_growth",
        description="Penalization of aggressive corporate balance-sheet expansion and abnormal capex spikes.",
        economic_rationale="Cooper, Gulen, & Schill (2008) & Titman et al. (2004): Fast balance sheet asset growth strongly forecasts future equity underperformance.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(-ts_delta(total_assets, 252) / (ts_delay(total_assets, 252) + 1.0), {decay})), {group}), -1)",
        typical_horizons=[15, 20, 30],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Post-Earnings VRP Crush Drift",
        category="peavrp_volatility_premia",
        description="Variance risk premium collapse following earnings announcements.",
        economic_rationale="Ball & Brown (1968) & Bollerslev et al. (2009): Post-earnings volatility crush triggers institutional relief drift and directional continuation.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(ts_delta(implied_volatility_mean_30 - historical_volatility_30, 5) * sign(ts_delta(eps, 60)), {decay})), {group}), -1)",
        typical_horizons=[10, 15, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Realized Jump Range Discontinuity",
        category="realized_jump_intensity",
        description="High-frequency price jump range expansion decomposed against realized baseline volatility.",
        economic_rationale="Amaya et al. (2015) & Nonejad (2013): Intraday jump variance shocks cause temporary liquidity vacuums and mean-reverting liquidity replenishment.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(-((high - low) / (close + 0.001) - historical_volatility_10), {decay})), {group}), -1)",
        typical_horizons=[10, 12, 15],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Structural Distance to Default Solvency",
        category="distance_to_default_debt",
        description="Merton structural default distance proxy scaling debt coverage by options volatility.",
        economic_rationale="Merton (1974) & Bharath & Shumway (2008): Firms with high equity buffers relative to total debt and low IV command structural solvency premia.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(((assets - debt_total) / (assets + 1.0)) / (implied_volatility_mean_30 + 0.01), {decay})), {group}), -1)",
        typical_horizons=[15, 18, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
    OptionArchetype(
        name="Macro Event Beta Uncertainty Drift",
        category="macro_fomc_cpi_drift",
        description="Scheduled macroeconomic announcement volatility crush and systematic beta premia.",
        economic_rationale="Savor & Wilson (2013) & Lucca & Moench (2015): Systematic macro announcements resolve uncertainty, driving high-beta equity rallies.",
        formula_template="trade_when(volume > adv20 * 0.8, group_neutralize(rank(ts_decay_linear(ts_covariance(returns, group_mean(returns, 100, market), 60) * (implied_volatility_call_30 / (implied_volatility_put_30 + 0.001)), {decay})), {group}), -1)",
        typical_horizons=[12, 15, 20],
        neutralization_groups=["subindustry", "sector"],
        is_high_confidence=True,
    ),
]


